[package]
edition = "2021"
name = "dgews"
version = "0.0.3"
authors = ["MrTitanHearted"]
description = "Easy toy windowing system for learning purposes only"
license = "MIT"
resolver = "2"
readme = "README.md"
homepage = "https://github.com/MrTitanHearted/dgews"
repository = "https://github.com/MrTitanHearted/dgews"
categories = [
    "GUI",
    "Win32",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies.winapi]
version = "0.3.9"
features = [
    "minwindef",
    "windef",
    "wingdi",
    "winuser",
    "libloaderapi",
    "dwmapi",
]
